/**
 * Generate Registry Script
 * 
 * Tự động quét folder /modules và sinh ra:
 * - registry.ts (cho frontend - import cả component)
 * - schemas.ts (cho Payload CMS - chỉ import schema config, không CSS)
 * 
 * Usage: npx tsx src/scripts/generate-registry.ts
 */

import fs from 'fs'
import path from 'path'

const MODULES_DIR = path.join(process.cwd(), 'src/components/modules')
const REGISTRY_FILE = path.join(MODULES_DIR, 'registry.ts')
const SCHEMAS_FILE = path.join(MODULES_DIR, 'schemas.ts')

interface ModuleInfo {
  folderName: string
  moduleKey: string
  moduleLabel: string
}

function extractModuleInfo(schemaPath: string, folderName: string): ModuleInfo | null {
  try {
    const content = fs.readFileSync(schemaPath, 'utf-8')
    
    // Extract moduleKey using regex
    const keyMatch = content.match(/export\s+const\s+moduleKey\s*=\s*['"`]([^'"`]+)['"`]/)
    const labelMatch = content.match(/export\s+const\s+moduleLabel\s*=\s*['"`]([^'"`]+)['"`]/)
    
    if (!keyMatch) {
      console.warn(`⚠️  No moduleKey found in ${schemaPath}`)
      return null
    }

    return {
      folderName,
      moduleKey: keyMatch[1],
      moduleLabel: labelMatch ? labelMatch[1] : folderName,
    }
  } catch (error) {
    console.warn(`⚠️  Error reading ${schemaPath}:`, error)
    return null
  }
}

async function generateRegistry() {
  console.log('🔍 Scanning modules directory...')
  
  // Ensure modules directory exists
  if (!fs.existsSync(MODULES_DIR)) {
    console.log('📁 Creating modules directory...')
    fs.mkdirSync(MODULES_DIR, { recursive: true })
  }

  // Get all directories in modules folder
  const entries = fs.readdirSync(MODULES_DIR, { withFileTypes: true })
  const folders = entries
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)

  console.log(`📦 Found ${folders.length} module folder(s)`)

  const modules: ModuleInfo[] = []
  
  // For schemas.ts (Payload CMS - no components)
  const schemaImports: string[] = []
  const schemaEntries: string[] = []
  
  // For registry.ts (Frontend - with components)
  const registryImports: string[] = []
  const moduleEntries: string[] = []
  const componentMapEntries: string[] = []

  for (const folder of folders) {
    const schemaPath = path.join(MODULES_DIR, folder, 'schema.ts')
    const indexPath = path.join(MODULES_DIR, folder, 'index.tsx')
    
    // Check if schema.ts exists
    if (!fs.existsSync(schemaPath)) {
      console.warn(`⚠️  Skipping ${folder}: no schema.ts found`)
      continue
    }

    const moduleInfo = extractModuleInfo(schemaPath, folder)
    if (!moduleInfo) continue

    modules.push(moduleInfo)

    // Generate safe variable name
    const varName = folder.replace(/[^a-zA-Z0-9]/g, '_')
    
    // Schema imports (for Payload CMS)
    schemaImports.push(`import * as ${varName}_Schema from './${folder}/schema'`)
    schemaEntries.push(`  ${varName}_Schema`)
    
    // Check if component exists for registry
    if (fs.existsSync(indexPath)) {
      registryImports.push(`import * as ${varName}_Schema from './${folder}/schema'`)
      registryImports.push(`import { ${folder} as ${varName}_Component } from './${folder}'`)
      moduleEntries.push(`  { config: ${varName}_Schema, Component: ${varName}_Component }`)
      componentMapEntries.push(`  [${varName}_Schema.moduleKey]: ${varName}_Component`)
    }
    
    console.log(`   ✅ ${folder} (key: ${moduleInfo.moduleKey})`)
  }

  // Generate schemas.ts (for Payload CMS - no CSS imports)
  const schemasContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx src/scripts/generate-registry.ts
 * Generated at: ${new Date().toISOString()}
 * 
 * This file contains ONLY schema configurations (no components).
 * Safe to import in Payload CMS collections without CSS issues.
 */

import type { Field } from 'payload'
${schemaImports.join('\n')}

// Schema configuration type
export interface SchemaConfig {
  moduleKey: string
  moduleLabel: string
  fields: Field[]
}

// All registered module schemas
export const SCHEMAS: SchemaConfig[] = [
${schemaEntries.join(',\n')}
]

// Get schema by key
export function getSchema(moduleKey: string): SchemaConfig | undefined {
  return SCHEMAS.find(s => s.moduleKey === moduleKey)
}

// Get template options for select field
export function getTemplateOptions() {
  return SCHEMAS.map(s => ({
    label: s.moduleLabel,
    value: s.moduleKey,
  }))
}
`

  fs.writeFileSync(SCHEMAS_FILE, schemasContent)
  console.log(`   📄 schemas.ts generated`)

  // Generate registry.ts (for Frontend - with components)
  const registryContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx src/scripts/generate-registry.ts
 * Generated at: ${new Date().toISOString()}
 * 
 * This file is auto-generated before each dev/build.
 * To add a new module:
 * 1. Create a folder in src/components/modules/[ModuleName]
 * 2. Add schema.ts with moduleKey and moduleLabel exports
 * 3. Add index.tsx with the component export
 * 4. Run npm run registry:generate
 */

import { ComponentType } from 'react'
${registryImports.length > 0 ? '\n' + registryImports.join('\n') : ''}

// Module configuration type
export interface ModuleConfig {
  moduleKey: string
  moduleLabel: string
  fields: any[]
}

// Module registry entry type
export interface ModuleEntry {
  config: ModuleConfig
  Component: ComponentType<{ data: any; slug?: string[] }>
}

// All registered modules
export const MODULES: ModuleEntry[] = [
${moduleEntries.join(',\n')}
]

// Quick lookup map: moduleKey -> Component
export const ComponentMap: Record<string, ComponentType<{ data: any; slug?: string[] }>> = {
${componentMapEntries.join(',\n')}
}

// Get module config by key
export function getModuleConfig(moduleKey: string): ModuleConfig | undefined {
  return MODULES.find(m => m.config.moduleKey === moduleKey)?.config
}

// Get component by key
export function getModuleComponent(moduleKey: string): ComponentType<{ data: any; slug?: string[] }> | undefined {
  return ComponentMap[moduleKey]
}
`

  fs.writeFileSync(REGISTRY_FILE, registryContent)
  console.log(`   📄 registry.ts generated`)
  
  console.log(`\n✅ Registry generated successfully!`)
  console.log(`   📦 Modules: ${modules.length}`)
  
  if (modules.length === 0) {
    console.log('\n💡 No modules found. To create a module:')
    console.log('   1. Create folder: src/components/modules/MyModule')
    console.log('   2. Add schema.ts with: export const moduleKey = "my-module"')
    console.log('   3. Add index.tsx with: export const MyModule = ({ data }) => ...')
  }
}

generateRegistry().catch(console.error)
