/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx src/scripts/generate-registry.ts
 * Generated at: 2026-01-26T04:11:46.915Z
 * 
 * This file is auto-generated before each dev/build.
 * To add a new module:
 * 1. Create a folder in src/components/modules/[ModuleName]
 * 2. Add schema.ts with moduleKey and moduleLabel exports
 * 3. Add index.tsx with the component export
 * 4. Run npm run registry:generate
 */

import { ComponentType } from 'react'

import * as AsiaToursTravelWeb_Schema from './AsiaToursTravelWeb/schema'
import { AsiaToursTravelWeb as AsiaToursTravelWeb_Component } from './AsiaToursTravelWeb'
import * as BasicLandingPage_Schema from './BasicLandingPage/schema'
import { BasicLandingPage as BasicLandingPage_Component } from './BasicLandingPage'
import * as BasicWebApp_Schema from './BasicWebApp/schema'
import { BasicWebApp as BasicWebApp_Component } from './BasicWebApp'

// Module configuration type
export interface ModuleConfig {
  moduleKey: string
  moduleLabel: string
  fields: any[]
}

// Module registry entry type
export interface ModuleEntry {
  config: ModuleConfig
  Component: ComponentType<{ data: any; slug?: string[] }>
}

// All registered modules
export const MODULES: ModuleEntry[] = [
  { config: AsiaToursTravelWeb_Schema, Component: AsiaToursTravelWeb_Component },
  { config: BasicLandingPage_Schema, Component: BasicLandingPage_Component },
  { config: BasicWebApp_Schema, Component: BasicWebApp_Component }
]

// Quick lookup map: moduleKey -> Component
export const ComponentMap: Record<string, ComponentType<{ data: any; slug?: string[] }>> = {
  [AsiaToursTravelWeb_Schema.moduleKey]: AsiaToursTravelWeb_Component,
  [BasicLandingPage_Schema.moduleKey]: BasicLandingPage_Component,
  [BasicWebApp_Schema.moduleKey]: BasicWebApp_Component
}

// Get module config by key
export function getModuleConfig(moduleKey: string): ModuleConfig | undefined {
  return MODULES.find(m => m.config.moduleKey === moduleKey)?.config
}

// Get component by key
export function getModuleComponent(moduleKey: string): ComponentType<{ data: any; slug?: string[] }> | undefined {
  return ComponentMap[moduleKey]
}
