/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx src/scripts/generate-registry.ts
 * Generated at: 2026-01-28T01:39:28.358Z
 * 
 * This file contains ONLY schema configurations (no components).
 * Safe to import in Payload CMS collections without CSS issues.
 */

import type { Field } from 'payload'
import * as AsiaToursTravelWeb_Schema from './AsiaToursTravelWeb/schema'
import * as BasicLandingPage_Schema from './BasicLandingPage/schema'
import * as BasicWebApp_Schema from './BasicWebApp/schema'

// Schema configuration type
export interface SchemaConfig {
  moduleKey: string
  moduleLabel: string
  fields: Field[]
}

// All registered module schemas
export const SCHEMAS: SchemaConfig[] = [
  AsiaToursTravelWeb_Schema,
  BasicLandingPage_Schema,
  BasicWebApp_Schema
]

// Get schema by key
export function getSchema(moduleKey: string): SchemaConfig | undefined {
  return SCHEMAS.find(s => s.moduleKey === moduleKey)
}

// Get template options for select field
export function getTemplateOptions() {
  return SCHEMAS.map(s => ({
    label: s.moduleLabel,
    value: s.moduleKey,
  }))
}
