/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    tours: Tour;
    'tour-categories': TourCategory;
    blogs: Blog;
    experiences: Experience;
    countries: Country;
    destinations: Destination;
    tags: Tag;
    faqs: Faq;
    'service-types': ServiceType;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    'tour-categories': TourCategoriesSelect<false> | TourCategoriesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'service-types': ServiceTypesSelect<false> | ServiceTypesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Quản lý các trang web cho từng tenant/subdomain
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Tên dễ nhớ để quản lý (ví dụ: "Landing Page Khuyến Mãi")
   */
  name: string;
  /**
   * Subdomain (ví dụ: "khuyenmai" -> khuyenmai.privatetour.asia)
   */
  subdomain: string;
  /**
   * Bật/tắt trang web này
   */
  isActive?: boolean | null;
  /**
   * Chọn template cho trang web
   */
  templateId: 'asia-tours-travel-web' | 'basic-landing-page' | 'basic-web-app';
  /**
   * Cấu hình SEO cho trang web
   */
  seo?: {
    /**
     * Tiêu đề hiển thị trên tab browser
     */
    title?: string | null;
    /**
     * Mô tả trang cho SEO (150-160 ký tự)
     */
    description?: string | null;
    /**
     * Ảnh hiển thị khi share trên mạng xã hội
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Nội dung cho template "Asia Tours Travel Website"
   */
  content_asia_tours_travel_web?: {
    siteSettings: {
      siteName: string;
      logo?: (number | null) | Media;
      contactPhone?: string | null;
      contactEmail?: string | null;
    };
    heroSection?: {
      slides?:
        | {
            image: number | Media;
            title?: string | null;
            subtitle?: string | null;
            link?: string | null;
            linkText?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    navigation?:
      | {
          label: string;
          href: string;
          children?:
            | {
                label?: string | null;
                href?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Select tours for the Multi-Country Grid section (Category: Multi-Country)
     */
    multiCountryTours?: (number | Tour)[] | null;
    /**
     * Select tours to display in the vertical wide-card list (e.g. "Featured Tours")
     */
    featuredTours?: (number | Tour)[] | null;
    /**
     * Select blogs to display on homepage
     */
    featuredBlogs?: (number | Blog)[] | null;
    bestSupport?:
      | {
          icon?: (number | null) | Media;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    tourStyles?:
      | {
          title: string;
          image: number | Media;
          description?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    uniqueExperiences?:
      | {
          title: string;
          location?: string | null;
          country?: string | null;
          image: number | Media;
          description?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    recentTravels?:
      | {
          title?: string | null;
          location?: string | null;
          image: number | Media;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
    locExp?: {
      stats?: {
        countries?: string | null;
        destinations?: string | null;
        experiences?: string | null;
        reviews?: string | null;
        guests?: string | null;
      };
      gallery?:
        | {
            image?: (number | null) | Media;
            name?: string | null;
            size?: ('crow-size-1' | 'crow-size-2' | 'crow-size-3') | null;
            id?: string | null;
          }[]
        | null;
    };
    footer?: {
      aboutText?: string | null;
      copyright?: string | null;
      socialLinks?:
        | {
            platform?: ('facebook' | 'twitter' | 'instagram' | 'youtube' | 'tripadvisor') | null;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
      footerPartners?:
        | {
            logo: number | Media;
            name?: string | null;
            link?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Nội dung cho template "Basic Landing Page (Static)"
   */
  content_basic_landing_page?: {
    /**
     * Tiêu đề chính hiển thị ở banner
     */
    heroTitle: string;
    /**
     * Mô tả ngắn bên dưới tiêu đề
     */
    heroSubtitle?: string | null;
    /**
     * Ảnh banner chính (khuyến nghị: 1920x1080)
     */
    heroBanner?: (number | null) | Media;
    ctaButton?: {
      text?: string | null;
      link?: string | null;
    };
    features?:
      | {
          /**
           * Emoji hoặc icon class (e.g., 🚀, ⭐)
           */
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    contactInfo?: {
      email?: string | null;
      phone?: string | null;
      address?: string | null;
    };
    footerText?: string | null;
  };
  /**
   * Nội dung cho template "Basic Web App (Dynamic)"
   */
  content_basic_web_app?: {
    /**
     * Tên ứng dụng hiển thị trên header
     */
    appName: string;
    /**
     * Mô tả ngắn về ứng dụng
     */
    appDescription?: string | null;
    /**
     * Màu chủ đạo của ứng dụng (hex code)
     */
    primaryColor?: string | null;
    apiConfig?: {
      /**
       * URL của API backend (e.g., https://api.example.com)
       */
      endpoint?: string | null;
      /**
       * API Key để xác thực (sẽ được truyền qua header)
       */
      apiKey?: string | null;
    };
    features?: {
      enableSearch?: boolean | null;
      enableDarkMode?: boolean | null;
      enableNotifications?: boolean | null;
    };
    menuItems?:
      | {
          label: string;
          href: string;
          /**
           * Emoji hoặc icon (e.g., 🏠, 📊)
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý tours cho các travel websites
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  /**
   * Ảnh đại diện chính cho tour (khuyến nghị: 800x600)
   */
  featuredImage?: (number | null) | Media;
  /**
   * Tên tour (VD: "Vietnam Discovery 12 Days")
   */
  title: string;
  /**
   * URL-friendly identifier (VD: "vietnam-discovery-12-days")
   */
  slug: string;
  /**
   * VD: "Private & Tailored Tour"
   */
  subtitle?: string | null;
  /**
   * Mô tả ngắn hiển thị trong tour card (max 200 ký tự)
   */
  shortDescription?: string | null;
  /**
   * This list is automatically populated and calculated based on the Detailed Itinerary
   */
  destinations?:
    | {
        destination: number | Destination;
        image?: (number | null) | Media;
        duration_days?: number | null;
        id?: string | null;
      }[]
    | null;
  countries: (number | Country)[];
  /**
   * Auto-calculated based on countries count
   */
  tourType?: ('single-country' | 'multi-country') | null;
  /**
   * Auto-generated (e.g. Vietnam Cambodia Laos Tours)
   */
  routeTitle?: string | null;
  /**
   * Auto-generated query key (e.g. vietnam-cambodia-laos)
   */
  routeSlug?: string | null;
  /**
   * Phân loại tour (VD: Luxury Tours, Family Tours)
   */
  categories?: (number | TourCategory)[] | null;
  /**
   * Thẻ tag cho tour (VD: History, Local Life)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Tự động tính từ Lịch trình chi tiết
   */
  duration?: string | null;
  /**
   * Giá khởi điểm
   */
  price?: number | null;
  /**
   * VD: "From $1,500 per person" hoặc "Price on request"
   */
  priceNote?: string | null;
  videoUrl?: string | null;
  priceOptions?:
    | {
        name?: string | null;
        price?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mô tả ngắn gọn các điểm nổi bật (Sử dụng Bullet List cho tiện lợi)
   */
  highlights?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lịch trình chi tiết từng ngày (Accordion View)
   */
  itinerary?:
    | {
        day: string;
        /**
         * Chọn điểm đến cụ thể để hệ thống tự động tổng hợp danh sách Destinations
         */
        location: number | Destination;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        services?:
          | {
              serviceType: number | ServiceType;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        meals?: ('Breakfast' | 'Lunch' | 'Dinner')[] | null;
        /**
         * Sử dụng Services breakdown cho thông tin Hotel mới
         */
        accommodation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Liệt kê các dịch vụ đã bao gồm trong tour (dạng rich text)
   */
  includes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Liệt kê các dịch vụ không bao gồm trong tour (dạng rich text)
   */
  excludes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs_accommodation?: {
    items?:
      | {
          /**
           * e.g. Day 1: Hanoi
           */
          day_title: string;
          options?:
            | {
                hotel_name: string;
                hotel_grade: 'Economy' | 'Deluxe' | 'Luxury';
                star_rating?: number | null;
                review_count?: number | null;
                trip_advisor_url?: string | null;
                image?: (number | null) | Media;
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  specs_experiences?: {
    items?: (number | Experience)[] | null;
  };
  specs_transport?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  specs_team?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  specs_meals?: {
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  specs_services?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tour thuộc tenant nào
   */
  tenant?: (number | null) | Tenant;
  /**
   * Hiển thị tour này trên website
   */
  isActive?: boolean | null;
  /**
   * Hiển thị trong danh sách featured tours
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý điểm đến (Cities, Provinces)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  /**
   * URL slug (e.g. ha-long-bay)
   */
  slug: string;
  country: number | Country;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geo?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý danh sách quốc gia
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * URL slug (e.g. vietnam)
   */
  slug: string;
  code?: string | null;
  region?: ('southeast-asia' | 'east-asia' | 'south-asia') | null;
  /**
   * Select specific FAQs to display on this country page.
   */
  faqs?: (number | Faq)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently Asked Questions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Auto-generated from question
   */
  slug?: string | null;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  countries?: (number | Country)[] | null;
  destinations?: (number | Destination)[] | null;
  tags?: (number | Tag)[] | null;
  tour_categories?: (number | TourCategory)[] | null;
  /**
   * Check this if the FAQ is generic and should appear on the Home Page.
   */
  is_general?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tag_code: string;
  tag_name: string;
  active?: ('Y' | 'N') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories for grouping tours (e.g. Luxury, Family)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-categories".
 */
export interface TourCategory {
  id: number;
  title: string;
  /**
   * URL slug (e.g., luxury-tours)
   */
  slug: string;
  /**
   * Banner image for the category page
   */
  heroImage?: (number | null) | Media;
  /**
   * Select specific FAQs to display on this category page.
   */
  faqs?: (number | Faq)[] | null;
  /**
   * Short description for SEO and page header
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types".
 */
export interface ServiceType {
  id: number;
  /**
   * e.g. TRF, GUI, HTL
   */
  code: string;
  name: string;
  /**
   * e.g. per vehicle, per day
   */
  defaultUnit?: string | null;
  isActive?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  duration?: string | null;
  /**
   * URL-friendly identifier
   */
  slug: string;
  image: number | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        label: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  short_description?: string | null;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  country?: (number | null) | Country;
  destination?: (number | null) | Destination;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quản lý blog posts cho các travel websites
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * Tiêu đề bài viết
   */
  title: string;
  /**
   * URL-friendly identifier (VD: "best-time-to-visit-vietnam")
   */
  slug: string;
  /**
   * Tên tác giả
   */
  author?: string | null;
  publishDate?: string | null;
  /**
   * Ảnh đại diện cho bài viết (khuyến nghị: 1200x630)
   */
  featuredImage?: (number | null) | Media;
  /**
   * Tóm tắt ngắn hiển thị trong blog listing (max 160 ký tự)
   */
  excerpt?: string | null;
  /**
   * Nội dung đầy đủ của bài viết - có thể chèn hình ảnh xen kẽ
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tags để phân loại bài viết
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Danh mục bài viết
   */
  category?: ('travel-tips' | 'destinations' | 'culture' | 'food' | 'adventure' | 'news') | null;
  /**
   * Tour liên quan đến bài viết này
   */
  relatedTour?: (number | null) | Tour;
  /**
   * Quốc gia liên quan
   */
  relatedCountries?: (number | Country)[] | null;
  /**
   * Điểm đến liên quan
   */
  relatedDestinations?: (number | Destination)[] | null;
  /**
   * Bài viết liên quan hiển thị ở cuối trang
   */
  relatedPosts?: (number | Blog)[] | null;
  /**
   * Blog thuộc tenant nào
   */
  tenant?: (number | null) | Tenant;
  /**
   * Xuất bản bài viết này
   */
  isPublished?: boolean | null;
  /**
   * Hiển thị trong featured posts
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'tour-categories';
        value: number | TourCategory;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'service-types';
        value: number | ServiceType;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  subdomain?: T;
  isActive?: T;
  templateId?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  content_asia_tours_travel_web?:
    | T
    | {
        siteSettings?:
          | T
          | {
              siteName?: T;
              logo?: T;
              contactPhone?: T;
              contactEmail?: T;
            };
        heroSection?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    link?: T;
                    linkText?: T;
                    id?: T;
                  };
            };
        navigation?:
          | T
          | {
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        multiCountryTours?: T;
        featuredTours?: T;
        featuredBlogs?: T;
        bestSupport?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        tourStyles?:
          | T
          | {
              title?: T;
              image?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        uniqueExperiences?:
          | T
          | {
              title?: T;
              location?: T;
              country?: T;
              image?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        recentTravels?:
          | T
          | {
              title?: T;
              location?: T;
              image?: T;
              link?: T;
              id?: T;
            };
        locExp?:
          | T
          | {
              stats?:
                | T
                | {
                    countries?: T;
                    destinations?: T;
                    experiences?: T;
                    reviews?: T;
                    guests?: T;
                  };
              gallery?:
                | T
                | {
                    image?: T;
                    name?: T;
                    size?: T;
                    id?: T;
                  };
            };
        footer?:
          | T
          | {
              aboutText?: T;
              copyright?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              footerPartners?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    link?: T;
                    id?: T;
                  };
            };
      };
  content_basic_landing_page?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        heroBanner?: T;
        ctaButton?:
          | T
          | {
              text?: T;
              link?: T;
            };
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        contactInfo?:
          | T
          | {
              email?: T;
              phone?: T;
              address?: T;
            };
        footerText?: T;
      };
  content_basic_web_app?:
    | T
    | {
        appName?: T;
        appDescription?: T;
        primaryColor?: T;
        apiConfig?:
          | T
          | {
              endpoint?: T;
              apiKey?: T;
            };
        features?:
          | T
          | {
              enableSearch?: T;
              enableDarkMode?: T;
              enableNotifications?: T;
            };
        menuItems?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  featuredImage?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  shortDescription?: T;
  destinations?:
    | T
    | {
        destination?: T;
        image?: T;
        duration_days?: T;
        id?: T;
      };
  countries?: T;
  tourType?: T;
  routeTitle?: T;
  routeSlug?: T;
  categories?: T;
  tags?: T;
  duration?: T;
  price?: T;
  priceNote?: T;
  videoUrl?: T;
  priceOptions?:
    | T
    | {
        name?: T;
        price?: T;
        description?: T;
        id?: T;
      };
  highlights?: T;
  itinerary?:
    | T
    | {
        day?: T;
        location?: T;
        content?: T;
        services?:
          | T
          | {
              serviceType?: T;
              description?: T;
              id?: T;
            };
        meals?: T;
        accommodation?: T;
        id?: T;
      };
  includes?: T;
  excludes?: T;
  specs_accommodation?:
    | T
    | {
        items?:
          | T
          | {
              day_title?: T;
              options?:
                | T
                | {
                    hotel_name?: T;
                    hotel_grade?: T;
                    star_rating?: T;
                    review_count?: T;
                    trip_advisor_url?: T;
                    image?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  specs_experiences?:
    | T
    | {
        items?: T;
      };
  specs_transport?:
    | T
    | {
        content?: T;
      };
  specs_team?:
    | T
    | {
        content?: T;
      };
  specs_meals?:
    | T
    | {
        description?: T;
      };
  specs_services?:
    | T
    | {
        content?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  tenant?: T;
  isActive?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-categories_select".
 */
export interface TourCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  faqs?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishDate?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  category?: T;
  relatedTour?: T;
  relatedCountries?: T;
  relatedDestinations?: T;
  relatedPosts?: T;
  tenant?: T;
  isPublished?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  duration?: T;
  slug?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  short_description?: T;
  description?: T;
  content?: T;
  location?: T;
  country?: T;
  destination?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  region?: T;
  faqs?: T;
  description?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  description?: T;
  featuredImage?: T;
  geo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tag_code?: T;
  tag_name?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  answer?: T;
  countries?: T;
  destinations?: T;
  tags?: T;
  tour_categories?: T;
  is_general?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types_select".
 */
export interface ServiceTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  defaultUnit?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}