/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const le_gal_size = pgEnum('le_gal_size', ['crow-size-1', 'crow-size-2', 'crow-size-3'])
export const social_platform = pgEnum('social_platform', [
  'facebook',
  'twitter',
  'instagram',
  'youtube',
  'tripadvisor',
])
export const enum_tenants_template_id = pgEnum('enum_tenants_template_id', [
  'asia-tours-travel-web',
  'basic-landing-page',
  'basic-web-app',
])
export const enum_tours_tour_tiers_code = pgEnum('enum_tours_tour_tiers_code', [
  'economy',
  'deluxe',
  'luxury',
])
export const enum_tours_itinerary_services_tier_overrides_tiers = pgEnum(
  'enum_tours_itinerary_services_tier_overrides_tiers',
  ['economy', 'deluxe', 'luxury'],
)
export const enum_tours_tour_type = pgEnum('enum_tours_tour_type', [
  'single-country',
  'multi-country',
])
export const enum_blogs_category = pgEnum('enum_blogs_category', [
  'travel-tips',
  'destinations',
  'culture',
  'food',
  'adventure',
  'news',
])
export const enum_countries_region = pgEnum('enum_countries_region', [
  'southeast-asia',
  'east-asia',
  'south-asia',
])
export const enum_tags_active = pgEnum('enum_tags_active', ['Y', 'N'])
export const enum_transit_hubs_type = pgEnum('enum_transit_hubs_type', [
  'airport',
  'train_station',
  'pier',
  'bus_station',
])
export const enum_services_status = pgEnum('enum_services_status', [
  'draft',
  'published',
  'inactive',
])
export const enum_services_level = pgEnum('enum_services_level', ['economy', 'deluxe', 'luxury'])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const tenants_content_asia_tours_travel_web_hero_section_slides = pgTable(
  'tenants_content_asia_tours_travel_web_hero_section_slides',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    title: varchar('title').default('Discover the Essence of Asia'),
    subtitle: varchar('subtitle'),
    link: varchar('link'),
    linkText: varchar('link_text').default('Explore Now'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_hero_section_slides_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_hero_section_slides_parent_id_idx').on(
      columns._parentID,
    ),
    index('tenants_content_asia_tours_travel_web_hero_section_slide_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_hero_section_slides_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_navigation_children = pgTable(
  'tenants_content_asia_tours_travel_web_navigation_children',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    href: varchar('href'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_navigation_children_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_navigation_children_parent_id_idx').on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants_content_asia_tours_travel_web_navigation.id],
      name: 'tenants_content_asia_tours_travel_web_navigation_children_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_navigation = pgTable(
  'tenants_content_asia_tours_travel_web_navigation',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    href: varchar('href'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_navigation_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_navigation_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_navigation_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_best_support = pgTable(
  'tenants_content_asia_tours_travel_web_best_support',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    title: varchar('title'),
    description: varchar('description'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_best_support_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_best_support_parent_id_idx').on(columns._parentID),
    index('tenants_content_asia_tours_travel_web_best_support_icon_idx').on(columns.icon),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_best_support_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_tour_styles = pgTable(
  'tenants_content_asia_tours_travel_web_tour_styles',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    link: varchar('link'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_tour_styles_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_tour_styles_parent_id_idx').on(columns._parentID),
    index('tenants_content_asia_tours_travel_web_tour_styles_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_tour_styles_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_unique_experiences = pgTable(
  'tenants_content_asia_tours_travel_web_unique_experiences',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    location: varchar('location'),
    country: varchar('country'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    link: varchar('link'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_unique_experiences_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_unique_experiences_parent_id_idx').on(
      columns._parentID,
    ),
    index('tenants_content_asia_tours_travel_web_unique_experiences_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_unique_experiences_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_faqs = pgTable(
  'tenants_content_asia_tours_travel_web_faqs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    question: varchar('question'),
    answer: varchar('answer'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_faqs_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_faqs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_faqs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_recent_travels = pgTable(
  'tenants_content_asia_tours_travel_web_recent_travels',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    location: varchar('location'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    link: varchar('link'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_recent_travels_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_recent_travels_parent_id_idx').on(
      columns._parentID,
    ),
    index('tenants_content_asia_tours_travel_web_recent_travels_ima_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_recent_travels_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const le_gal = pgTable(
  'le_gal',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    name: varchar('name'),
    size: le_gal_size('size').default('crow-size-1'),
  },
  (columns) => [
    index('le_gal_order_idx').on(columns._order),
    index('le_gal_parent_id_idx').on(columns._parentID),
    index('le_gal_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'le_gal_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_footer_social_links = pgTable(
  'tenants_content_asia_tours_travel_web_footer_social_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: social_platform('platform'),
    url: varchar('url'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_footer_social_links_order_idx').on(columns._order),
    index('tenants_content_asia_tours_travel_web_footer_social_links_parent_id_idx').on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_footer_social_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_asia_tours_travel_web_footer_footer_partners = pgTable(
  'tenants_content_asia_tours_travel_web_footer_footer_partners',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    name: varchar('name'),
    link: varchar('link'),
  },
  (columns) => [
    index('tenants_content_asia_tours_travel_web_footer_footer_partners_order_idx').on(
      columns._order,
    ),
    index('tenants_content_asia_tours_travel_web_footer_footer_partners_parent_id_idx').on(
      columns._parentID,
    ),
    index('tenants_content_asia_tours_travel_web_footer_footer_part_idx').on(columns.logo),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_asia_tours_travel_web_footer_footer_partners_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_basic_landing_page_features = pgTable(
  'tenants_content_basic_landing_page_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: varchar('icon'),
    title: varchar('title'),
    description: varchar('description'),
  },
  (columns) => [
    index('tenants_content_basic_landing_page_features_order_idx').on(columns._order),
    index('tenants_content_basic_landing_page_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_basic_landing_page_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants_content_basic_web_app_menu_items = pgTable(
  'tenants_content_basic_web_app_menu_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    href: varchar('href'),
    icon: varchar('icon'),
  },
  (columns) => [
    index('tenants_content_basic_web_app_menu_items_order_idx').on(columns._order),
    index('tenants_content_basic_web_app_menu_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tenants.id],
      name: 'tenants_content_basic_web_app_menu_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tenants = pgTable(
  'tenants',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    subdomain: varchar('subdomain').notNull(),
    isActive: boolean('is_active').default(true),
    templateId: enum_tenants_template_id('template_id').notNull().default('asia-tours-travel-web'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_ogImage: integer('seo_og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    content_asia_tours_travel_web_siteSettings_siteName: varchar(
      'content_asia_tours_travel_web_site_settings_site_name',
    ).default('Asia Tours'),
    content_asia_tours_travel_web_siteSettings_logo: integer(
      'content_asia_tours_travel_web_site_settings_logo_id',
    ).references(() => media.id, {
      onDelete: 'set null',
    }),
    content_asia_tours_travel_web_siteSettings_contactPhone: varchar(
      'content_asia_tours_travel_web_site_settings_contact_phone',
    ),
    content_asia_tours_travel_web_siteSettings_contactEmail: varchar(
      'content_asia_tours_travel_web_site_settings_contact_email',
    ),
    content_asia_tours_travel_web_locExp_stats_countries: varchar(
      'content_asia_tours_travel_web_loc_exp_stats_countries',
    ).default('18'),
    content_asia_tours_travel_web_locExp_stats_destinations: varchar(
      'content_asia_tours_travel_web_loc_exp_stats_destinations',
    ).default('316'),
    content_asia_tours_travel_web_locExp_stats_experiences: varchar(
      'content_asia_tours_travel_web_loc_exp_stats_experiences',
    ).default('900+'),
    content_asia_tours_travel_web_locExp_stats_reviews: varchar(
      'content_asia_tours_travel_web_loc_exp_stats_reviews',
    ).default('98%'),
    content_asia_tours_travel_web_locExp_stats_guests: varchar(
      'content_asia_tours_travel_web_loc_exp_stats_guests',
    ).default('20,000+'),
    content_asia_tours_travel_web_footer_aboutText: varchar(
      'content_asia_tours_travel_web_footer_about_text',
    ),
    content_asia_tours_travel_web_footer_copyright: varchar(
      'content_asia_tours_travel_web_footer_copyright',
    ).default('© 2024 Asia Tours. All rights reserved.'),
    content_basic_landing_page_heroTitle: varchar('content_basic_landing_page_hero_title'),
    content_basic_landing_page_heroSubtitle: varchar('content_basic_landing_page_hero_subtitle'),
    content_basic_landing_page_heroBanner: integer(
      'content_basic_landing_page_hero_banner_id',
    ).references(() => media.id, {
      onDelete: 'set null',
    }),
    content_basic_landing_page_ctaButton_text: varchar(
      'content_basic_landing_page_cta_button_text',
    ).default('Liên hệ ngay'),
    content_basic_landing_page_ctaButton_link: varchar(
      'content_basic_landing_page_cta_button_link',
    ).default('#contact'),
    content_basic_landing_page_contactInfo_email: varchar(
      'content_basic_landing_page_contact_info_email',
    ),
    content_basic_landing_page_contactInfo_phone: varchar(
      'content_basic_landing_page_contact_info_phone',
    ),
    content_basic_landing_page_contactInfo_address: varchar(
      'content_basic_landing_page_contact_info_address',
    ),
    content_basic_landing_page_footerText: varchar(
      'content_basic_landing_page_footer_text',
    ).default('© 2025 All rights reserved.'),
    content_basic_web_app_appName: varchar('content_basic_web_app_app_name'),
    content_basic_web_app_appDescription: varchar('content_basic_web_app_app_description'),
    content_basic_web_app_primaryColor: varchar('content_basic_web_app_primary_color').default(
      '#667eea',
    ),
    content_basic_web_app_apiConfig_endpoint: varchar('content_basic_web_app_api_config_endpoint'),
    content_basic_web_app_apiConfig_apiKey: varchar('content_basic_web_app_api_config_api_key'),
    content_basic_web_app_features_enableSearch: boolean(
      'content_basic_web_app_features_enable_search',
    ).default(true),
    content_basic_web_app_features_enableDarkMode: boolean(
      'content_basic_web_app_features_enable_dark_mode',
    ).default(true),
    content_basic_web_app_features_enableNotifications: boolean(
      'content_basic_web_app_features_enable_notifications',
    ).default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tenants_subdomain_idx').on(columns.subdomain),
    index('tenants_seo_seo_og_image_idx').on(columns.seo_ogImage),
    index('tenants_content_asia_tours_travel_web_site_settings_cont_idx').on(
      columns.content_asia_tours_travel_web_siteSettings_logo,
    ),
    index('tenants_content_basic_landing_page_content_basic_landing_idx').on(
      columns.content_basic_landing_page_heroBanner,
    ),
    index('tenants_updated_at_idx').on(columns.updatedAt),
    index('tenants_created_at_idx').on(columns.createdAt),
  ],
)

export const tenants_rels = pgTable(
  'tenants_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    toursID: integer('tours_id'),
    blogsID: integer('blogs_id'),
  },
  (columns) => [
    index('tenants_rels_order_idx').on(columns.order),
    index('tenants_rels_parent_idx').on(columns.parent),
    index('tenants_rels_path_idx').on(columns.path),
    index('tenants_rels_tours_id_idx').on(columns.toursID),
    index('tenants_rels_blogs_id_idx').on(columns.blogsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tenants.id],
      name: 'tenants_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'tenants_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blogsID']],
      foreignColumns: [blogs.id],
      name: 'tenants_rels_blogs_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_districts = pgTable(
  'tours_districts',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    district: integer('district_id')
      .notNull()
      .references(() => districts.id, {
        onDelete: 'set null',
      }),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    duration_days: numeric('duration_days', { mode: 'number' }),
  },
  (columns) => [
    index('tours_districts_order_idx').on(columns._order),
    index('tours_districts_parent_id_idx').on(columns._parentID),
    index('tours_districts_district_idx').on(columns.district),
    index('tours_districts_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_districts_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_tour_tiers = pgTable(
  'tours_tour_tiers',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    code: enum_tours_tour_tiers_code('code').notNull(),
    name: varchar('name').notNull(),
    price: numeric('price', { mode: 'number' }),
    description: varchar('description'),
  },
  (columns) => [
    index('tours_tour_tiers_order_idx').on(columns._order),
    index('tours_tour_tiers_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_tour_tiers_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_itinerary_services_tier_overrides_tiers = pgTable(
  'tours_itinerary_services_tier_overrides_tiers',
  {
    order: integer('order').notNull(),
    parent: varchar('parent_id').notNull(),
    value: enum_tours_itinerary_services_tier_overrides_tiers('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('tours_itinerary_services_tier_overrides_tiers_order_idx').on(columns.order),
    index('tours_itinerary_services_tier_overrides_tiers_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tours_itinerary_services_tier_overrides.id],
      name: 'tours_itinerary_services_tier_overrides_tiers_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_itinerary_services_tier_overrides = pgTable(
  'tours_itinerary_services_tier_overrides',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    service: integer('service_id')
      .notNull()
      .references(() => services.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('tours_itinerary_services_tier_overrides_order_idx').on(columns._order),
    index('tours_itinerary_services_tier_overrides_parent_id_idx').on(columns._parentID),
    index('tours_itinerary_services_tier_overrides_service_idx').on(columns.service),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours_itinerary_services.id],
      name: 'tours_itinerary_services_tier_overrides_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_itinerary_services_alternatives = pgTable(
  'tours_itinerary_services_alternatives',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    service: integer('service_id')
      .notNull()
      .references(() => services.id, {
        onDelete: 'set null',
      }),
    priceModifier: numeric('price_modifier', { mode: 'number' }),
  },
  (columns) => [
    index('tours_itinerary_services_alternatives_order_idx').on(columns._order),
    index('tours_itinerary_services_alternatives_parent_id_idx').on(columns._parentID),
    index('tours_itinerary_services_alternatives_service_idx').on(columns.service),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours_itinerary_services.id],
      name: 'tours_itinerary_services_alternatives_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_itinerary_services = pgTable(
  'tours_itinerary_services',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    service: integer('service_id')
      .notNull()
      .references(() => services.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('tours_itinerary_services_order_idx').on(columns._order),
    index('tours_itinerary_services_parent_id_idx').on(columns._parentID),
    index('tours_itinerary_services_service_idx').on(columns.service),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours_itinerary.id],
      name: 'tours_itinerary_services_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_itinerary = pgTable(
  'tours_itinerary',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    day: varchar('day').notNull(),
    content: jsonb('content').notNull(),
  },
  (columns) => [
    index('tours_itinerary_order_idx').on(columns._order),
    index('tours_itinerary_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_itinerary_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours_gallery = pgTable(
  'tours_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('tours_gallery_order_idx').on(columns._order),
    index('tours_gallery_parent_id_idx').on(columns._parentID),
    index('tours_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [tours.id],
      name: 'tours_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const tours = pgTable(
  'tours',
  {
    id: serial('id').primaryKey(),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    subtitle: varchar('subtitle'),
    shortDescription: varchar('short_description'),
    tourType: enum_tours_tour_type('tour_type'),
    routeTitle: varchar('route_title'),
    routeSlug: varchar('route_slug'),
    duration: varchar('duration'),
    price: numeric('price', { mode: 'number' }),
    priceNote: varchar('price_note'),
    videoUrl: varchar('video_url'),
    highlights: jsonb('highlights'),
    includes: jsonb('includes'),
    excludes: jsonb('excludes'),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    isActive: boolean('is_active').default(true),
    isFeatured: boolean('is_featured').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('tours_featured_image_idx').on(columns.featuredImage),
    uniqueIndex('tours_slug_idx').on(columns.slug),
    index('tours_route_slug_idx').on(columns.routeSlug),
    index('tours_tenant_idx').on(columns.tenant),
    index('tours_updated_at_idx').on(columns.updatedAt),
    index('tours_created_at_idx').on(columns.createdAt),
  ],
)

export const tours_rels = pgTable(
  'tours_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    countriesID: integer('countries_id'),
    'tour-categoriesID': integer('tour_categories_id'),
    tagsID: integer('tags_id'),
    districtsID: integer('districts_id'),
  },
  (columns) => [
    index('tours_rels_order_idx').on(columns.order),
    index('tours_rels_parent_idx').on(columns.parent),
    index('tours_rels_path_idx').on(columns.path),
    index('tours_rels_countries_id_idx').on(columns.countriesID),
    index('tours_rels_tour_categories_id_idx').on(columns['tour-categoriesID']),
    index('tours_rels_tags_id_idx').on(columns.tagsID),
    index('tours_rels_districts_id_idx').on(columns.districtsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tours.id],
      name: 'tours_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'tours_rels_countries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tour-categoriesID']],
      foreignColumns: [tour_categories.id],
      name: 'tours_rels_tour_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'tours_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['districtsID']],
      foreignColumns: [districts.id],
      name: 'tours_rels_districts_fk',
    }).onDelete('cascade'),
  ],
)

export const tour_categories = pgTable(
  'tour_categories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tour_categories_title_idx').on(columns.title),
    uniqueIndex('tour_categories_slug_idx').on(columns.slug),
    index('tour_categories_hero_image_idx').on(columns.heroImage),
    index('tour_categories_updated_at_idx').on(columns.updatedAt),
    index('tour_categories_created_at_idx').on(columns.createdAt),
  ],
)

export const tour_categories_rels = pgTable(
  'tour_categories_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    faqsID: integer('faqs_id'),
  },
  (columns) => [
    index('tour_categories_rels_order_idx').on(columns.order),
    index('tour_categories_rels_parent_idx').on(columns.parent),
    index('tour_categories_rels_path_idx').on(columns.path),
    index('tour_categories_rels_faqs_id_idx').on(columns.faqsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tour_categories.id],
      name: 'tour_categories_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'tour_categories_rels_faqs_fk',
    }).onDelete('cascade'),
  ],
)

export const blogs_tags = pgTable(
  'blogs_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').notNull(),
  },
  (columns) => [
    index('blogs_tags_order_idx').on(columns._order),
    index('blogs_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [blogs.id],
      name: 'blogs_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const blogs = pgTable(
  'blogs',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    author: varchar('author'),
    publishDate: timestamp('publish_date', { mode: 'string', withTimezone: true, precision: 3 }),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    category: enum_blogs_category('category'),
    relatedTour: integer('related_tour_id').references(() => tours.id, {
      onDelete: 'set null',
    }),
    tenant: integer('tenant_id').references(() => tenants.id, {
      onDelete: 'set null',
    }),
    isPublished: boolean('is_published').default(false),
    isFeatured: boolean('is_featured').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('blogs_slug_idx').on(columns.slug),
    index('blogs_featured_image_idx').on(columns.featuredImage),
    index('blogs_related_tour_idx').on(columns.relatedTour),
    index('blogs_tenant_idx').on(columns.tenant),
    index('blogs_updated_at_idx').on(columns.updatedAt),
    index('blogs_created_at_idx').on(columns.createdAt),
  ],
)

export const blogs_rels = pgTable(
  'blogs_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    countriesID: integer('countries_id'),
    districtsID: integer('districts_id'),
    blogsID: integer('blogs_id'),
  },
  (columns) => [
    index('blogs_rels_order_idx').on(columns.order),
    index('blogs_rels_parent_idx').on(columns.parent),
    index('blogs_rels_path_idx').on(columns.path),
    index('blogs_rels_countries_id_idx').on(columns.countriesID),
    index('blogs_rels_districts_id_idx').on(columns.districtsID),
    index('blogs_rels_blogs_id_idx').on(columns.blogsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [blogs.id],
      name: 'blogs_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'blogs_rels_countries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['districtsID']],
      foreignColumns: [districts.id],
      name: 'blogs_rels_districts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blogsID']],
      foreignColumns: [blogs.id],
      name: 'blogs_rels_blogs_fk',
    }).onDelete('cascade'),
  ],
)

export const experiences_gallery = pgTable(
  'experiences_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => [
    index('experiences_gallery_order_idx').on(columns._order),
    index('experiences_gallery_parent_id_idx').on(columns._parentID),
    index('experiences_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [experiences.id],
      name: 'experiences_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const experiences_tags = pgTable(
  'experiences_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    icon: varchar('icon'),
  },
  (columns) => [
    index('experiences_tags_order_idx').on(columns._order),
    index('experiences_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [experiences.id],
      name: 'experiences_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const experiences = pgTable(
  'experiences',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    duration: varchar('duration'),
    slug: varchar('slug').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    short_description: varchar('short_description'),
    description: varchar('description').notNull(),
    content: jsonb('content'),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    country: integer('country_id').references(() => countries.id, {
      onDelete: 'set null',
    }),
    district: integer('district_id').references(() => districts.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('experiences_slug_idx').on(columns.slug),
    index('experiences_image_idx').on(columns.image),
    index('experiences_country_idx').on(columns.country),
    index('experiences_district_idx').on(columns.district),
    index('experiences_updated_at_idx').on(columns.updatedAt),
    index('experiences_created_at_idx').on(columns.createdAt),
  ],
)

export const countries = pgTable(
  'countries',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    code: varchar('code'),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    region: enum_countries_region('region'),
    description: jsonb('description'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('countries_name_idx').on(columns.name),
    uniqueIndex('countries_slug_idx').on(columns.slug),
    index('countries_featured_image_idx').on(columns.featuredImage),
    index('countries_updated_at_idx').on(columns.updatedAt),
    index('countries_created_at_idx').on(columns.createdAt),
  ],
)

export const countries_rels = pgTable(
  'countries_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    faqsID: integer('faqs_id'),
  },
  (columns) => [
    index('countries_rels_order_idx').on(columns.order),
    index('countries_rels_parent_idx').on(columns.parent),
    index('countries_rels_path_idx').on(columns.path),
    index('countries_rels_faqs_id_idx').on(columns.faqsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [countries.id],
      name: 'countries_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'countries_rels_faqs_fk',
    }).onDelete('cascade'),
  ],
)

export const districts = pgTable(
  'districts',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    country: integer('country_id')
      .notNull()
      .references(() => countries.id, {
        onDelete: 'set null',
      }),
    isHub: boolean('is_hub').default(false),
    logistics_nearestAirport: integer('logistics_nearest_airport_id').references(
      () => transit_hubs.id,
      {
        onDelete: 'set null',
      },
    ),
    logistics_nearestTrainStation: integer('logistics_nearest_train_station_id').references(
      () => transit_hubs.id,
      {
        onDelete: 'set null',
      },
    ),
    logistics_transferNotes: varchar('logistics_transfer_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('districts_slug_idx').on(columns.slug),
    index('districts_country_idx').on(columns.country),
    index('districts_logistics_logistics_nearest_airport_idx').on(columns.logistics_nearestAirport),
    index('districts_logistics_logistics_nearest_train_station_idx').on(
      columns.logistics_nearestTrainStation,
    ),
    index('districts_updated_at_idx').on(columns.updatedAt),
    index('districts_created_at_idx').on(columns.createdAt),
  ],
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    tag_code: varchar('tag_code').notNull(),
    tag_name: varchar('tag_name').notNull(),
    active: enum_tags_active('active').default('Y'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tags_tag_code_idx').on(columns.tag_code),
    index('tags_updated_at_idx').on(columns.updatedAt),
    index('tags_created_at_idx').on(columns.createdAt),
  ],
)

export const faqs = pgTable(
  'faqs',
  {
    id: serial('id').primaryKey(),
    question: varchar('question').notNull(),
    slug: varchar('slug'),
    answer: jsonb('answer').notNull(),
    is_general: boolean('is_general').default(false),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('faqs_updated_at_idx').on(columns.updatedAt),
    index('faqs_created_at_idx').on(columns.createdAt),
  ],
)

export const faqs_rels = pgTable(
  'faqs_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    countriesID: integer('countries_id'),
    districtsID: integer('districts_id'),
    tagsID: integer('tags_id'),
    'tour-categoriesID': integer('tour_categories_id'),
  },
  (columns) => [
    index('faqs_rels_order_idx').on(columns.order),
    index('faqs_rels_parent_idx').on(columns.parent),
    index('faqs_rels_path_idx').on(columns.path),
    index('faqs_rels_countries_id_idx').on(columns.countriesID),
    index('faqs_rels_districts_id_idx').on(columns.districtsID),
    index('faqs_rels_tags_id_idx').on(columns.tagsID),
    index('faqs_rels_tour_categories_id_idx').on(columns['tour-categoriesID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [faqs.id],
      name: 'faqs_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'faqs_rels_countries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['districtsID']],
      foreignColumns: [districts.id],
      name: 'faqs_rels_districts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'faqs_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tour-categoriesID']],
      foreignColumns: [tour_categories.id],
      name: 'faqs_rels_tour_categories_fk',
    }).onDelete('cascade'),
  ],
)

export const service_types = pgTable(
  'service_types',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    name: varchar('name').notNull(),
    defaultUnit: varchar('default_unit'),
    isActive: boolean('is_active').default(true),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('service_types_code_idx').on(columns.code),
    index('service_types_updated_at_idx').on(columns.updatedAt),
    index('service_types_created_at_idx').on(columns.createdAt),
  ],
)

export const experience_themes = pgTable(
  'experience_themes',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    name: varchar('name').notNull(),
    serviceType: integer('service_type_id')
      .notNull()
      .references(() => service_types.id, {
        onDelete: 'set null',
      }),
    description: varchar('description'),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('experience_themes_code_idx').on(columns.code),
    index('experience_themes_service_type_idx').on(columns.serviceType),
    index('experience_themes_updated_at_idx').on(columns.updatedAt),
    index('experience_themes_created_at_idx').on(columns.createdAt),
  ],
)

export const markets = pgTable(
  'markets',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    name: varchar('name').notNull(),
    isActive: boolean('is_active').default(true),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('markets_code_idx').on(columns.code),
    index('markets_updated_at_idx').on(columns.updatedAt),
    index('markets_created_at_idx').on(columns.createdAt),
  ],
)

export const transit_hubs = pgTable(
  'transit_hubs',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    code: varchar('code'),
    type: enum_transit_hubs_type('type').notNull(),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    district: integer('district_id')
      .notNull()
      .references(() => districts.id, {
        onDelete: 'set null',
      }),
    country: integer('country_id')
      .notNull()
      .references(() => countries.id, {
        onDelete: 'set null',
      }),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('transit_hubs_district_idx').on(columns.district),
    index('transit_hubs_country_idx').on(columns.country),
    index('transit_hubs_updated_at_idx').on(columns.updatedAt),
    index('transit_hubs_created_at_idx').on(columns.createdAt),
  ],
)

export const services = pgTable(
  'services',
  {
    id: serial('id').primaryKey(),
    serviceCode: varchar('service_code').notNull(),
    status: enum_services_status('status').default('draft'),
    title: varchar('title').notNull(),
    level: enum_services_level('level'),
    description: jsonb('description'),
    type: integer('type_id')
      .notNull()
      .references(() => service_types.id, {
        onDelete: 'set null',
      }),
    district: integer('district_id')
      .notNull()
      .references(() => districts.id, {
        onDelete: 'set null',
      }),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    unit: varchar('unit'),
    leadTime: varchar('lead_time'),
    cancellationPolicy: varchar('cancellation_policy'),
    notes: jsonb('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('services_service_code_idx').on(columns.serviceCode),
    index('services_type_idx').on(columns.type),
    index('services_district_idx').on(columns.district),
    index('services_updated_at_idx').on(columns.updatedAt),
    index('services_created_at_idx').on(columns.createdAt),
  ],
)

export const services_rels = pgTable(
  'services_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    experiencesID: integer('experiences_id'),
    blogsID: integer('blogs_id'),
    marketsID: integer('markets_id'),
  },
  (columns) => [
    index('services_rels_order_idx').on(columns.order),
    index('services_rels_parent_idx').on(columns.parent),
    index('services_rels_path_idx').on(columns.path),
    index('services_rels_experiences_id_idx').on(columns.experiencesID),
    index('services_rels_blogs_id_idx').on(columns.blogsID),
    index('services_rels_markets_id_idx').on(columns.marketsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [services.id],
      name: 'services_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['experiencesID']],
      foreignColumns: [experiences.id],
      name: 'services_rels_experiences_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blogsID']],
      foreignColumns: [blogs.id],
      name: 'services_rels_blogs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['marketsID']],
      foreignColumns: [markets.id],
      name: 'services_rels_markets_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    tenantsID: integer('tenants_id'),
    toursID: integer('tours_id'),
    'tour-categoriesID': integer('tour_categories_id'),
    blogsID: integer('blogs_id'),
    experiencesID: integer('experiences_id'),
    countriesID: integer('countries_id'),
    districtsID: integer('districts_id'),
    tagsID: integer('tags_id'),
    faqsID: integer('faqs_id'),
    'service-typesID': integer('service_types_id'),
    'experience-themesID': integer('experience_themes_id'),
    marketsID: integer('markets_id'),
    'transit-hubsID': integer('transit_hubs_id'),
    servicesID: integer('services_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_tenants_id_idx').on(columns.tenantsID),
    index('payload_locked_documents_rels_tours_id_idx').on(columns.toursID),
    index('payload_locked_documents_rels_tour_categories_id_idx').on(columns['tour-categoriesID']),
    index('payload_locked_documents_rels_blogs_id_idx').on(columns.blogsID),
    index('payload_locked_documents_rels_experiences_id_idx').on(columns.experiencesID),
    index('payload_locked_documents_rels_countries_id_idx').on(columns.countriesID),
    index('payload_locked_documents_rels_districts_id_idx').on(columns.districtsID),
    index('payload_locked_documents_rels_tags_id_idx').on(columns.tagsID),
    index('payload_locked_documents_rels_faqs_id_idx').on(columns.faqsID),
    index('payload_locked_documents_rels_service_types_id_idx').on(columns['service-typesID']),
    index('payload_locked_documents_rels_experience_themes_id_idx').on(
      columns['experience-themesID'],
    ),
    index('payload_locked_documents_rels_markets_id_idx').on(columns.marketsID),
    index('payload_locked_documents_rels_transit_hubs_id_idx').on(columns['transit-hubsID']),
    index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tenantsID']],
      foreignColumns: [tenants.id],
      name: 'payload_locked_documents_rels_tenants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['toursID']],
      foreignColumns: [tours.id],
      name: 'payload_locked_documents_rels_tours_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tour-categoriesID']],
      foreignColumns: [tour_categories.id],
      name: 'payload_locked_documents_rels_tour_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blogsID']],
      foreignColumns: [blogs.id],
      name: 'payload_locked_documents_rels_blogs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['experiencesID']],
      foreignColumns: [experiences.id],
      name: 'payload_locked_documents_rels_experiences_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'payload_locked_documents_rels_countries_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['districtsID']],
      foreignColumns: [districts.id],
      name: 'payload_locked_documents_rels_districts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['faqsID']],
      foreignColumns: [faqs.id],
      name: 'payload_locked_documents_rels_faqs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['service-typesID']],
      foreignColumns: [service_types.id],
      name: 'payload_locked_documents_rels_service_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['experience-themesID']],
      foreignColumns: [experience_themes.id],
      name: 'payload_locked_documents_rels_experience_themes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['marketsID']],
      foreignColumns: [markets.id],
      name: 'payload_locked_documents_rels_markets_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transit-hubsID']],
      foreignColumns: [transit_hubs.id],
      name: 'payload_locked_documents_rels_transit_hubs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_tenants_content_asia_tours_travel_web_hero_section_slides = relations(
  tenants_content_asia_tours_travel_web_hero_section_slides,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_hero_section_slides._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_heroSection_slides',
    }),
    image: one(media, {
      fields: [tenants_content_asia_tours_travel_web_hero_section_slides.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_navigation_children = relations(
  tenants_content_asia_tours_travel_web_navigation_children,
  ({ one }) => ({
    _parentID: one(tenants_content_asia_tours_travel_web_navigation, {
      fields: [tenants_content_asia_tours_travel_web_navigation_children._parentID],
      references: [tenants_content_asia_tours_travel_web_navigation.id],
      relationName: 'children',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_navigation = relations(
  tenants_content_asia_tours_travel_web_navigation,
  ({ one, many }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_navigation._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_navigation',
    }),
    children: many(tenants_content_asia_tours_travel_web_navigation_children, {
      relationName: 'children',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_best_support = relations(
  tenants_content_asia_tours_travel_web_best_support,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_best_support._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_bestSupport',
    }),
    icon: one(media, {
      fields: [tenants_content_asia_tours_travel_web_best_support.icon],
      references: [media.id],
      relationName: 'icon',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_tour_styles = relations(
  tenants_content_asia_tours_travel_web_tour_styles,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_tour_styles._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_tourStyles',
    }),
    image: one(media, {
      fields: [tenants_content_asia_tours_travel_web_tour_styles.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_unique_experiences = relations(
  tenants_content_asia_tours_travel_web_unique_experiences,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_unique_experiences._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_uniqueExperiences',
    }),
    image: one(media, {
      fields: [tenants_content_asia_tours_travel_web_unique_experiences.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_faqs = relations(
  tenants_content_asia_tours_travel_web_faqs,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_faqs._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_faqs',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_recent_travels = relations(
  tenants_content_asia_tours_travel_web_recent_travels,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_recent_travels._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_recentTravels',
    }),
    image: one(media, {
      fields: [tenants_content_asia_tours_travel_web_recent_travels.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_le_gal = relations(le_gal, ({ one }) => ({
  _parentID: one(tenants, {
    fields: [le_gal._parentID],
    references: [tenants.id],
    relationName: 'content_asia_tours_travel_web_locExp_gallery',
  }),
  image: one(media, {
    fields: [le_gal.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_tenants_content_asia_tours_travel_web_footer_social_links = relations(
  tenants_content_asia_tours_travel_web_footer_social_links,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_footer_social_links._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_footer_socialLinks',
    }),
  }),
)
export const relations_tenants_content_asia_tours_travel_web_footer_footer_partners = relations(
  tenants_content_asia_tours_travel_web_footer_footer_partners,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_asia_tours_travel_web_footer_footer_partners._parentID],
      references: [tenants.id],
      relationName: 'content_asia_tours_travel_web_footer_footerPartners',
    }),
    logo: one(media, {
      fields: [tenants_content_asia_tours_travel_web_footer_footer_partners.logo],
      references: [media.id],
      relationName: 'logo',
    }),
  }),
)
export const relations_tenants_content_basic_landing_page_features = relations(
  tenants_content_basic_landing_page_features,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_basic_landing_page_features._parentID],
      references: [tenants.id],
      relationName: 'content_basic_landing_page_features',
    }),
  }),
)
export const relations_tenants_content_basic_web_app_menu_items = relations(
  tenants_content_basic_web_app_menu_items,
  ({ one }) => ({
    _parentID: one(tenants, {
      fields: [tenants_content_basic_web_app_menu_items._parentID],
      references: [tenants.id],
      relationName: 'content_basic_web_app_menuItems',
    }),
  }),
)
export const relations_tenants_rels = relations(tenants_rels, ({ one }) => ({
  parent: one(tenants, {
    fields: [tenants_rels.parent],
    references: [tenants.id],
    relationName: '_rels',
  }),
  toursID: one(tours, {
    fields: [tenants_rels.toursID],
    references: [tours.id],
    relationName: 'tours',
  }),
  blogsID: one(blogs, {
    fields: [tenants_rels.blogsID],
    references: [blogs.id],
    relationName: 'blogs',
  }),
}))
export const relations_tenants = relations(tenants, ({ one, many }) => ({
  seo_ogImage: one(media, {
    fields: [tenants.seo_ogImage],
    references: [media.id],
    relationName: 'seo_ogImage',
  }),
  content_asia_tours_travel_web_siteSettings_logo: one(media, {
    fields: [tenants.content_asia_tours_travel_web_siteSettings_logo],
    references: [media.id],
    relationName: 'content_asia_tours_travel_web_siteSettings_logo',
  }),
  content_asia_tours_travel_web_heroSection_slides: many(
    tenants_content_asia_tours_travel_web_hero_section_slides,
    {
      relationName: 'content_asia_tours_travel_web_heroSection_slides',
    },
  ),
  content_asia_tours_travel_web_navigation: many(tenants_content_asia_tours_travel_web_navigation, {
    relationName: 'content_asia_tours_travel_web_navigation',
  }),
  content_asia_tours_travel_web_bestSupport: many(
    tenants_content_asia_tours_travel_web_best_support,
    {
      relationName: 'content_asia_tours_travel_web_bestSupport',
    },
  ),
  content_asia_tours_travel_web_tourStyles: many(
    tenants_content_asia_tours_travel_web_tour_styles,
    {
      relationName: 'content_asia_tours_travel_web_tourStyles',
    },
  ),
  content_asia_tours_travel_web_uniqueExperiences: many(
    tenants_content_asia_tours_travel_web_unique_experiences,
    {
      relationName: 'content_asia_tours_travel_web_uniqueExperiences',
    },
  ),
  content_asia_tours_travel_web_faqs: many(tenants_content_asia_tours_travel_web_faqs, {
    relationName: 'content_asia_tours_travel_web_faqs',
  }),
  content_asia_tours_travel_web_recentTravels: many(
    tenants_content_asia_tours_travel_web_recent_travels,
    {
      relationName: 'content_asia_tours_travel_web_recentTravels',
    },
  ),
  content_asia_tours_travel_web_locExp_gallery: many(le_gal, {
    relationName: 'content_asia_tours_travel_web_locExp_gallery',
  }),
  content_asia_tours_travel_web_footer_socialLinks: many(
    tenants_content_asia_tours_travel_web_footer_social_links,
    {
      relationName: 'content_asia_tours_travel_web_footer_socialLinks',
    },
  ),
  content_asia_tours_travel_web_footer_footerPartners: many(
    tenants_content_asia_tours_travel_web_footer_footer_partners,
    {
      relationName: 'content_asia_tours_travel_web_footer_footerPartners',
    },
  ),
  content_basic_landing_page_heroBanner: one(media, {
    fields: [tenants.content_basic_landing_page_heroBanner],
    references: [media.id],
    relationName: 'content_basic_landing_page_heroBanner',
  }),
  content_basic_landing_page_features: many(tenants_content_basic_landing_page_features, {
    relationName: 'content_basic_landing_page_features',
  }),
  content_basic_web_app_menuItems: many(tenants_content_basic_web_app_menu_items, {
    relationName: 'content_basic_web_app_menuItems',
  }),
  _rels: many(tenants_rels, {
    relationName: '_rels',
  }),
}))
export const relations_tours_districts = relations(tours_districts, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_districts._parentID],
    references: [tours.id],
    relationName: 'districts',
  }),
  district: one(districts, {
    fields: [tours_districts.district],
    references: [districts.id],
    relationName: 'district',
  }),
  image: one(media, {
    fields: [tours_districts.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_tours_tour_tiers = relations(tours_tour_tiers, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_tour_tiers._parentID],
    references: [tours.id],
    relationName: 'tourTiers',
  }),
}))
export const relations_tours_itinerary_services_tier_overrides_tiers = relations(
  tours_itinerary_services_tier_overrides_tiers,
  ({ one }) => ({
    parent: one(tours_itinerary_services_tier_overrides, {
      fields: [tours_itinerary_services_tier_overrides_tiers.parent],
      references: [tours_itinerary_services_tier_overrides.id],
      relationName: 'tiers',
    }),
  }),
)
export const relations_tours_itinerary_services_tier_overrides = relations(
  tours_itinerary_services_tier_overrides,
  ({ one, many }) => ({
    _parentID: one(tours_itinerary_services, {
      fields: [tours_itinerary_services_tier_overrides._parentID],
      references: [tours_itinerary_services.id],
      relationName: 'tierOverrides',
    }),
    tiers: many(tours_itinerary_services_tier_overrides_tiers, {
      relationName: 'tiers',
    }),
    service: one(services, {
      fields: [tours_itinerary_services_tier_overrides.service],
      references: [services.id],
      relationName: 'service',
    }),
  }),
)
export const relations_tours_itinerary_services_alternatives = relations(
  tours_itinerary_services_alternatives,
  ({ one }) => ({
    _parentID: one(tours_itinerary_services, {
      fields: [tours_itinerary_services_alternatives._parentID],
      references: [tours_itinerary_services.id],
      relationName: 'alternatives',
    }),
    service: one(services, {
      fields: [tours_itinerary_services_alternatives.service],
      references: [services.id],
      relationName: 'service',
    }),
  }),
)
export const relations_tours_itinerary_services = relations(
  tours_itinerary_services,
  ({ one, many }) => ({
    _parentID: one(tours_itinerary, {
      fields: [tours_itinerary_services._parentID],
      references: [tours_itinerary.id],
      relationName: 'services',
    }),
    service: one(services, {
      fields: [tours_itinerary_services.service],
      references: [services.id],
      relationName: 'service',
    }),
    tierOverrides: many(tours_itinerary_services_tier_overrides, {
      relationName: 'tierOverrides',
    }),
    alternatives: many(tours_itinerary_services_alternatives, {
      relationName: 'alternatives',
    }),
  }),
)
export const relations_tours_itinerary = relations(tours_itinerary, ({ one, many }) => ({
  _parentID: one(tours, {
    fields: [tours_itinerary._parentID],
    references: [tours.id],
    relationName: 'itinerary',
  }),
  services: many(tours_itinerary_services, {
    relationName: 'services',
  }),
}))
export const relations_tours_gallery = relations(tours_gallery, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_gallery._parentID],
    references: [tours.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [tours_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_tours_rels = relations(tours_rels, ({ one }) => ({
  parent: one(tours, {
    fields: [tours_rels.parent],
    references: [tours.id],
    relationName: '_rels',
  }),
  countriesID: one(countries, {
    fields: [tours_rels.countriesID],
    references: [countries.id],
    relationName: 'countries',
  }),
  'tour-categoriesID': one(tour_categories, {
    fields: [tours_rels['tour-categoriesID']],
    references: [tour_categories.id],
    relationName: 'tour-categories',
  }),
  tagsID: one(tags, {
    fields: [tours_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  districtsID: one(districts, {
    fields: [tours_rels.districtsID],
    references: [districts.id],
    relationName: 'districts',
  }),
}))
export const relations_tours = relations(tours, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [tours.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  districts: many(tours_districts, {
    relationName: 'districts',
  }),
  tourTiers: many(tours_tour_tiers, {
    relationName: 'tourTiers',
  }),
  itinerary: many(tours_itinerary, {
    relationName: 'itinerary',
  }),
  gallery: many(tours_gallery, {
    relationName: 'gallery',
  }),
  tenant: one(tenants, {
    fields: [tours.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  _rels: many(tours_rels, {
    relationName: '_rels',
  }),
}))
export const relations_tour_categories_rels = relations(tour_categories_rels, ({ one }) => ({
  parent: one(tour_categories, {
    fields: [tour_categories_rels.parent],
    references: [tour_categories.id],
    relationName: '_rels',
  }),
  faqsID: one(faqs, {
    fields: [tour_categories_rels.faqsID],
    references: [faqs.id],
    relationName: 'faqs',
  }),
}))
export const relations_tour_categories = relations(tour_categories, ({ one, many }) => ({
  heroImage: one(media, {
    fields: [tour_categories.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  _rels: many(tour_categories_rels, {
    relationName: '_rels',
  }),
}))
export const relations_blogs_tags = relations(blogs_tags, ({ one }) => ({
  _parentID: one(blogs, {
    fields: [blogs_tags._parentID],
    references: [blogs.id],
    relationName: 'tags',
  }),
}))
export const relations_blogs_rels = relations(blogs_rels, ({ one }) => ({
  parent: one(blogs, {
    fields: [blogs_rels.parent],
    references: [blogs.id],
    relationName: '_rels',
  }),
  countriesID: one(countries, {
    fields: [blogs_rels.countriesID],
    references: [countries.id],
    relationName: 'countries',
  }),
  districtsID: one(districts, {
    fields: [blogs_rels.districtsID],
    references: [districts.id],
    relationName: 'districts',
  }),
  blogsID: one(blogs, {
    fields: [blogs_rels.blogsID],
    references: [blogs.id],
    relationName: 'blogs',
  }),
}))
export const relations_blogs = relations(blogs, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [blogs.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  tags: many(blogs_tags, {
    relationName: 'tags',
  }),
  relatedTour: one(tours, {
    fields: [blogs.relatedTour],
    references: [tours.id],
    relationName: 'relatedTour',
  }),
  tenant: one(tenants, {
    fields: [blogs.tenant],
    references: [tenants.id],
    relationName: 'tenant',
  }),
  _rels: many(blogs_rels, {
    relationName: '_rels',
  }),
}))
export const relations_experiences_gallery = relations(experiences_gallery, ({ one }) => ({
  _parentID: one(experiences, {
    fields: [experiences_gallery._parentID],
    references: [experiences.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [experiences_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_experiences_tags = relations(experiences_tags, ({ one }) => ({
  _parentID: one(experiences, {
    fields: [experiences_tags._parentID],
    references: [experiences.id],
    relationName: 'tags',
  }),
}))
export const relations_experiences = relations(experiences, ({ one, many }) => ({
  image: one(media, {
    fields: [experiences.image],
    references: [media.id],
    relationName: 'image',
  }),
  gallery: many(experiences_gallery, {
    relationName: 'gallery',
  }),
  tags: many(experiences_tags, {
    relationName: 'tags',
  }),
  country: one(countries, {
    fields: [experiences.country],
    references: [countries.id],
    relationName: 'country',
  }),
  district: one(districts, {
    fields: [experiences.district],
    references: [districts.id],
    relationName: 'district',
  }),
}))
export const relations_countries_rels = relations(countries_rels, ({ one }) => ({
  parent: one(countries, {
    fields: [countries_rels.parent],
    references: [countries.id],
    relationName: '_rels',
  }),
  faqsID: one(faqs, {
    fields: [countries_rels.faqsID],
    references: [faqs.id],
    relationName: 'faqs',
  }),
}))
export const relations_countries = relations(countries, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [countries.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  _rels: many(countries_rels, {
    relationName: '_rels',
  }),
}))
export const relations_districts = relations(districts, ({ one }) => ({
  country: one(countries, {
    fields: [districts.country],
    references: [countries.id],
    relationName: 'country',
  }),
  logistics_nearestAirport: one(transit_hubs, {
    fields: [districts.logistics_nearestAirport],
    references: [transit_hubs.id],
    relationName: 'logistics_nearestAirport',
  }),
  logistics_nearestTrainStation: one(transit_hubs, {
    fields: [districts.logistics_nearestTrainStation],
    references: [transit_hubs.id],
    relationName: 'logistics_nearestTrainStation',
  }),
}))
export const relations_tags = relations(tags, () => ({}))
export const relations_faqs_rels = relations(faqs_rels, ({ one }) => ({
  parent: one(faqs, {
    fields: [faqs_rels.parent],
    references: [faqs.id],
    relationName: '_rels',
  }),
  countriesID: one(countries, {
    fields: [faqs_rels.countriesID],
    references: [countries.id],
    relationName: 'countries',
  }),
  districtsID: one(districts, {
    fields: [faqs_rels.districtsID],
    references: [districts.id],
    relationName: 'districts',
  }),
  tagsID: one(tags, {
    fields: [faqs_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
  'tour-categoriesID': one(tour_categories, {
    fields: [faqs_rels['tour-categoriesID']],
    references: [tour_categories.id],
    relationName: 'tour-categories',
  }),
}))
export const relations_faqs = relations(faqs, ({ many }) => ({
  _rels: many(faqs_rels, {
    relationName: '_rels',
  }),
}))
export const relations_service_types = relations(service_types, () => ({}))
export const relations_experience_themes = relations(experience_themes, ({ one }) => ({
  serviceType: one(service_types, {
    fields: [experience_themes.serviceType],
    references: [service_types.id],
    relationName: 'serviceType',
  }),
}))
export const relations_markets = relations(markets, () => ({}))
export const relations_transit_hubs = relations(transit_hubs, ({ one }) => ({
  district: one(districts, {
    fields: [transit_hubs.district],
    references: [districts.id],
    relationName: 'district',
  }),
  country: one(countries, {
    fields: [transit_hubs.country],
    references: [countries.id],
    relationName: 'country',
  }),
}))
export const relations_services_rels = relations(services_rels, ({ one }) => ({
  parent: one(services, {
    fields: [services_rels.parent],
    references: [services.id],
    relationName: '_rels',
  }),
  experiencesID: one(experiences, {
    fields: [services_rels.experiencesID],
    references: [experiences.id],
    relationName: 'experiences',
  }),
  blogsID: one(blogs, {
    fields: [services_rels.blogsID],
    references: [blogs.id],
    relationName: 'blogs',
  }),
  marketsID: one(markets, {
    fields: [services_rels.marketsID],
    references: [markets.id],
    relationName: 'markets',
  }),
}))
export const relations_services = relations(services, ({ one, many }) => ({
  type: one(service_types, {
    fields: [services.type],
    references: [service_types.id],
    relationName: 'type',
  }),
  district: one(districts, {
    fields: [services.district],
    references: [districts.id],
    relationName: 'district',
  }),
  _rels: many(services_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    tenantsID: one(tenants, {
      fields: [payload_locked_documents_rels.tenantsID],
      references: [tenants.id],
      relationName: 'tenants',
    }),
    toursID: one(tours, {
      fields: [payload_locked_documents_rels.toursID],
      references: [tours.id],
      relationName: 'tours',
    }),
    'tour-categoriesID': one(tour_categories, {
      fields: [payload_locked_documents_rels['tour-categoriesID']],
      references: [tour_categories.id],
      relationName: 'tour-categories',
    }),
    blogsID: one(blogs, {
      fields: [payload_locked_documents_rels.blogsID],
      references: [blogs.id],
      relationName: 'blogs',
    }),
    experiencesID: one(experiences, {
      fields: [payload_locked_documents_rels.experiencesID],
      references: [experiences.id],
      relationName: 'experiences',
    }),
    countriesID: one(countries, {
      fields: [payload_locked_documents_rels.countriesID],
      references: [countries.id],
      relationName: 'countries',
    }),
    districtsID: one(districts, {
      fields: [payload_locked_documents_rels.districtsID],
      references: [districts.id],
      relationName: 'districts',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    faqsID: one(faqs, {
      fields: [payload_locked_documents_rels.faqsID],
      references: [faqs.id],
      relationName: 'faqs',
    }),
    'service-typesID': one(service_types, {
      fields: [payload_locked_documents_rels['service-typesID']],
      references: [service_types.id],
      relationName: 'service-types',
    }),
    'experience-themesID': one(experience_themes, {
      fields: [payload_locked_documents_rels['experience-themesID']],
      references: [experience_themes.id],
      relationName: 'experience-themes',
    }),
    marketsID: one(markets, {
      fields: [payload_locked_documents_rels.marketsID],
      references: [markets.id],
      relationName: 'markets',
    }),
    'transit-hubsID': one(transit_hubs, {
      fields: [payload_locked_documents_rels['transit-hubsID']],
      references: [transit_hubs.id],
      relationName: 'transit-hubs',
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: 'services',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  le_gal_size: typeof le_gal_size
  social_platform: typeof social_platform
  enum_tenants_template_id: typeof enum_tenants_template_id
  enum_tours_tour_tiers_code: typeof enum_tours_tour_tiers_code
  enum_tours_itinerary_services_tier_overrides_tiers: typeof enum_tours_itinerary_services_tier_overrides_tiers
  enum_tours_tour_type: typeof enum_tours_tour_type
  enum_blogs_category: typeof enum_blogs_category
  enum_countries_region: typeof enum_countries_region
  enum_tags_active: typeof enum_tags_active
  enum_transit_hubs_type: typeof enum_transit_hubs_type
  enum_services_status: typeof enum_services_status
  enum_services_level: typeof enum_services_level
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  tenants_content_asia_tours_travel_web_hero_section_slides: typeof tenants_content_asia_tours_travel_web_hero_section_slides
  tenants_content_asia_tours_travel_web_navigation_children: typeof tenants_content_asia_tours_travel_web_navigation_children
  tenants_content_asia_tours_travel_web_navigation: typeof tenants_content_asia_tours_travel_web_navigation
  tenants_content_asia_tours_travel_web_best_support: typeof tenants_content_asia_tours_travel_web_best_support
  tenants_content_asia_tours_travel_web_tour_styles: typeof tenants_content_asia_tours_travel_web_tour_styles
  tenants_content_asia_tours_travel_web_unique_experiences: typeof tenants_content_asia_tours_travel_web_unique_experiences
  tenants_content_asia_tours_travel_web_faqs: typeof tenants_content_asia_tours_travel_web_faqs
  tenants_content_asia_tours_travel_web_recent_travels: typeof tenants_content_asia_tours_travel_web_recent_travels
  le_gal: typeof le_gal
  tenants_content_asia_tours_travel_web_footer_social_links: typeof tenants_content_asia_tours_travel_web_footer_social_links
  tenants_content_asia_tours_travel_web_footer_footer_partners: typeof tenants_content_asia_tours_travel_web_footer_footer_partners
  tenants_content_basic_landing_page_features: typeof tenants_content_basic_landing_page_features
  tenants_content_basic_web_app_menu_items: typeof tenants_content_basic_web_app_menu_items
  tenants: typeof tenants
  tenants_rels: typeof tenants_rels
  tours_districts: typeof tours_districts
  tours_tour_tiers: typeof tours_tour_tiers
  tours_itinerary_services_tier_overrides_tiers: typeof tours_itinerary_services_tier_overrides_tiers
  tours_itinerary_services_tier_overrides: typeof tours_itinerary_services_tier_overrides
  tours_itinerary_services_alternatives: typeof tours_itinerary_services_alternatives
  tours_itinerary_services: typeof tours_itinerary_services
  tours_itinerary: typeof tours_itinerary
  tours_gallery: typeof tours_gallery
  tours: typeof tours
  tours_rels: typeof tours_rels
  tour_categories: typeof tour_categories
  tour_categories_rels: typeof tour_categories_rels
  blogs_tags: typeof blogs_tags
  blogs: typeof blogs
  blogs_rels: typeof blogs_rels
  experiences_gallery: typeof experiences_gallery
  experiences_tags: typeof experiences_tags
  experiences: typeof experiences
  countries: typeof countries
  countries_rels: typeof countries_rels
  districts: typeof districts
  tags: typeof tags
  faqs: typeof faqs
  faqs_rels: typeof faqs_rels
  service_types: typeof service_types
  experience_themes: typeof experience_themes
  markets: typeof markets
  transit_hubs: typeof transit_hubs
  services: typeof services
  services_rels: typeof services_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_tenants_content_asia_tours_travel_web_hero_section_slides: typeof relations_tenants_content_asia_tours_travel_web_hero_section_slides
  relations_tenants_content_asia_tours_travel_web_navigation_children: typeof relations_tenants_content_asia_tours_travel_web_navigation_children
  relations_tenants_content_asia_tours_travel_web_navigation: typeof relations_tenants_content_asia_tours_travel_web_navigation
  relations_tenants_content_asia_tours_travel_web_best_support: typeof relations_tenants_content_asia_tours_travel_web_best_support
  relations_tenants_content_asia_tours_travel_web_tour_styles: typeof relations_tenants_content_asia_tours_travel_web_tour_styles
  relations_tenants_content_asia_tours_travel_web_unique_experiences: typeof relations_tenants_content_asia_tours_travel_web_unique_experiences
  relations_tenants_content_asia_tours_travel_web_faqs: typeof relations_tenants_content_asia_tours_travel_web_faqs
  relations_tenants_content_asia_tours_travel_web_recent_travels: typeof relations_tenants_content_asia_tours_travel_web_recent_travels
  relations_le_gal: typeof relations_le_gal
  relations_tenants_content_asia_tours_travel_web_footer_social_links: typeof relations_tenants_content_asia_tours_travel_web_footer_social_links
  relations_tenants_content_asia_tours_travel_web_footer_footer_partners: typeof relations_tenants_content_asia_tours_travel_web_footer_footer_partners
  relations_tenants_content_basic_landing_page_features: typeof relations_tenants_content_basic_landing_page_features
  relations_tenants_content_basic_web_app_menu_items: typeof relations_tenants_content_basic_web_app_menu_items
  relations_tenants_rels: typeof relations_tenants_rels
  relations_tenants: typeof relations_tenants
  relations_tours_districts: typeof relations_tours_districts
  relations_tours_tour_tiers: typeof relations_tours_tour_tiers
  relations_tours_itinerary_services_tier_overrides_tiers: typeof relations_tours_itinerary_services_tier_overrides_tiers
  relations_tours_itinerary_services_tier_overrides: typeof relations_tours_itinerary_services_tier_overrides
  relations_tours_itinerary_services_alternatives: typeof relations_tours_itinerary_services_alternatives
  relations_tours_itinerary_services: typeof relations_tours_itinerary_services
  relations_tours_itinerary: typeof relations_tours_itinerary
  relations_tours_gallery: typeof relations_tours_gallery
  relations_tours_rels: typeof relations_tours_rels
  relations_tours: typeof relations_tours
  relations_tour_categories_rels: typeof relations_tour_categories_rels
  relations_tour_categories: typeof relations_tour_categories
  relations_blogs_tags: typeof relations_blogs_tags
  relations_blogs_rels: typeof relations_blogs_rels
  relations_blogs: typeof relations_blogs
  relations_experiences_gallery: typeof relations_experiences_gallery
  relations_experiences_tags: typeof relations_experiences_tags
  relations_experiences: typeof relations_experiences
  relations_countries_rels: typeof relations_countries_rels
  relations_countries: typeof relations_countries
  relations_districts: typeof relations_districts
  relations_tags: typeof relations_tags
  relations_faqs_rels: typeof relations_faqs_rels
  relations_faqs: typeof relations_faqs
  relations_service_types: typeof relations_service_types
  relations_experience_themes: typeof relations_experience_themes
  relations_markets: typeof relations_markets
  relations_transit_hubs: typeof relations_transit_hubs
  relations_services_rels: typeof relations_services_rels
  relations_services: typeof relations_services
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
